const post = require('./post');

module.exports = async (sms, credentials = {}) => {
  if (process.env.DEBUG) {
    sms = '1111';
    credentials = {
      // Can be generated by session user name, in uppercase
      login: process.env.DEBUG_LOGIN,
      // Can be generated https://click.alfa-bank.by/webBank2/helpNew/security.xhtml
      password: process.env.DEBUG_PASSWORD
    };
  }

  const data = JSON.stringify({
    sms,
    ...credentials,
    approve: true,
    deviceId: process.env.KSUID,
  });

  const result = await post(
    '/individual/1.0.0/registration/confirmRegistration',
    'application/json',
    data,
  );

  return JSON.parse(result);
};
